wandb_version: 1

batch_size:
  value: 32
feature_type:
  value: relu
ffn_dim:
  value: 1024
hidden_dim:
  value: 128
learning_rate:
  value: 5.236275278435739e-05
mask_ratio:
  value: 0.2
num_heads:
  value: 4
num_layers:
  value: 4
ree_base:
  value: 100
weight_decay:
  value: 0.0001
