wandb_version: 1

batch_size:
  value: 32
feature_type:
  value: sqr
ffn_dim:
  value: 2048
hidden_dim:
  value: 256
learning_rate:
  value: 0.00017285014878790363
mask_ratio:
  value: 0.3
num_heads:
  value: 4
num_layers:
  value: 2
ree_base:
  value: 100
weight_decay:
  value: 1.0e-05
