wandb_version: 1

batch_size:
  value: 32
feature_type:
  value: elu+1
ffn_dim:
  value: 512
hidden_dim:
  value: 512
learning_rate:
  value: 0.0004368655425669898
mask_ratio:
  value: 0.15
num_heads:
  value: 4
num_layers:
  value: 2
ree_base:
  value: 100
weight_decay:
  value: 0
